GET http://localhost:3000/books HTTP/1.1

###
GET http://localhost:3000/books/1 HTTP/1.1

###
POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
  "name": "Agua del cielo",
  "author": "Victor",
  "year": 2012
}

###
PUT http://localhost:3000/books/7 HTTP/1.1
Content-Type: application/json

{
  "name": "Cambio de Nombre"
 
}

###
DELETE http://localhost:3000/books/5 HTTP/1.1